### ISSUE TITLE
Ecto 3 support.

### ISSUE THREAD

**Issue by kapilpipaliya** [BenMorganIO/condo#1]
Is this library support ecto 3?

**Comment by BenMorganIO** [comment]
Honestly, to get Ecto 3 support shouldn't be hard. I know because I trudged through a lot of Ecto's source code for this library. Do you need Ecto 3 support? If so, I'll see what I can do.

**Comment by kapilpipaliya** [comment]
yes, I need ecto 3 support. I tried for full day to fix triplex library for ecto 3, but i am not expert. i also posted issue to them, I just finally made postgresql function as a workaround and using it.

**Comment by BenMorganIO** [comment]
@kapilpipaliya yeah, I also want to move to Ecto 3 and I still know how to get around the Ecto SQL stuff. You'll probably see an update from me around this week or next week or next.

**Comment by kapilpipaliya** [comment]
Thanks

**Comment by abarr** [comment]
Hi @BenMorganIO,

I am also looking for Ecto 3 support. Let me know if you need a hand, I am happy to help.

Andrew

**Comment by BenMorganIO** [comment]
Thanks, @abarr. I really should get to this. The haul of features I'm working on is finishing up. Once that's done I'll have time. If you'd like to take a stab at it, it would be more than appreciated. I'll review it and do my best to get it in.

**Comment by BenMorganIO** [comment]
@abarr Are you currently using this library? If so, any PRs for docs and whatnot would be great and how you've been using it. I'm really interested.

**Comment by abarr** [comment]
@BenMorganIO sorry for the delay replying I have a deadline coming up for the project and needed to work on it. I am not using the lib but if you can wait another week I will allocate some time (At the moment I have written/borrowed code to get me to the next milestone but would prefer it was in a lib)

**Comment by BenMorganIO** [comment]
Alright, got this done. I apologize that this took 2 months to do.

Please begin using 0.2.0. If you notice any problems, don't hesitate to open an issue and I'll take a good look at it.
